// packages/react/src/Within.tsx
import clsx from "clsx";
import {
  type ButtonHTMLAttributes,
  type CSSProperties,
} from "react";
import { useToggleId } from "./internal";


export interface WithinProps extends Omit<ButtonHTMLAttributes<HTMLButtonElement>, "children"> {
  duration?: number;
}

export function Within({
  duration = 500,
  className,
  type = "button",
  title = "Toggle theme",
  "aria-label": ariaLabel = "Toggle theme",
  ...props
}: WithinProps) {

  const toggleId = useToggleId();


  const clipMainId = `toggles.dev-within-main-${toggleId}`;


  return (
    <button
      type={type}
      title={title}
      aria-label={ariaLabel}
      className={className}
      {...props}
    >
<svg
        width="1em"
        height="1em"
        viewBox="0 0 32 32"
        aria-hidden="true"
        fill={"currentColor"}
        style={{ "--toggles-within--duration": `${duration}ms` } as CSSProperties}
      >
            <defs>
        <clipPath id={clipMainId}>
            <path d={"M0 0h32v32h-32ZM6 16A1 1 0 0026 16 1 1 0 006 16"} />
        </clipPath>
      </defs>
      <g clipPath={`url(#${clipMainId})`}>
        <path d={"M30.7 21.3 27.1 16l3.7-5.3c.4-.5.1-1.3-.6-1.4l-6.3-1.1-1.1-6.3c-.1-.6-.8-.9-1.4-.6L16 5l-5.4-3.7c-.5-.4-1.3-.1-1.4.6l-1 6.3-6.4 1.1c-.6.1-.9.9-.6 1.3L4.9 16l-3.7 5.3c-.4.5-.1 1.3.6 1.4l6.3 1.1 1.1 6.3c.1.6.8.9 1.4.6l5.3-3.7 5.3 3.7c.5.4 1.3.1 1.4-.6l1.1-6.3 6.3-1.1c.8-.1 1.1-.8.7-1.4zM16 25.1c-5.1 0-9.1-4.1-9.1-9.1 0-5.1 4.1-9.1 9.1-9.1s9.1 4.1 9.1 9.1c0 5.1-4 9.1-9.1 9.1z"} className={clsx("[transform-origin:center]", "toggles-dev--[transform-origin:center]", "[transition:transform_var(--toggles-within--duration)_cubic-bezier(0,0,0,1.25)]", "toggles-dev--[transition:transform_var(--toggles-within--duration)_cubic-bezier(0,0,0,1.25)]", "dark:[transform:scale(0.65)]", "dark:toggles-dev--[transform:scale(0.65)]")} />
      </g>
      <path d={"M16 7.7c-4.6 0-8.2 3.7-8.2 8.2s3.6 8.4 8.2 8.4 8.2-3.7 8.2-8.2-3.6-8.4-8.2-8.4zm0 14.4c-3.4 0-6.1-2.9-6.1-6.2s2.7-6.1 6.1-6.1c3.4 0 6.1 2.9 6.1 6.2s-2.7 6.1-6.1 6.1z"} className={clsx("[transform-origin:center]", "toggles-dev--[transform-origin:center]", "[transition:transform_var(--toggles-within--duration)_cubic-bezier(0,0,0,1.25)]", "toggles-dev--[transition:transform_var(--toggles-within--duration)_cubic-bezier(0,0,0,1.25)]", "dark:[transform:scale(1.5)]", "dark:toggles-dev--[transform:scale(1.5)]")} />
      <path d={"M16 9.5c-3.6 0-6.4 2.9-6.4 6.4s2.8 6.5 6.4 6.5 6.4-2.9 6.4-6.4-2.8-6.5-6.4-6.5z"} className={clsx("[transform-origin:center]", "toggles-dev--[transform-origin:center]", "[transition:transform_var(--toggles-within--duration)_cubic-bezier(0,0,0,1.25)]", "toggles-dev--[transition:transform_var(--toggles-within--duration)_cubic-bezier(0,0,0,1.25)]", "dark:[transform:translate3d(3px,-3px,0)_scale(1.2)]", "dark:toggles-dev--[transform:translate3d(3px,-3px,0)_scale(1.2)]")} />
      </svg>
    </button>
  );
}

// packages/svelte/src/Within.svelte
<script lang="ts">
  import clsx from "clsx";
  import type { HTMLButtonAttributes } from "svelte/elements";
  import { createToggleId } from "./internal";


  interface $$Props extends Omit<HTMLButtonAttributes, "children"> {
    duration?: number;
    ariaLabel?: string;
    class?: string;
  }

  export let duration = 500;
  export let type: HTMLButtonAttributes["type"] = "button";
  export let title = "Toggle theme";
  export let ariaLabel = "Toggle theme";
  let className = "";
  export { className as class };


  const toggleId = createToggleId("within");

  const clipMainId = `toggles.dev-within-main-${toggleId}`;


</script>

<button
  type={type}
  title={title}
  aria-label={ariaLabel}
  class={className}
  on:click
  {...$$restProps}
>
<svg
  width="1em"
  height="1em"
  viewBox="0 0 32 32"
  aria-hidden="true"
  fill={"currentColor"}
  style={`--toggles-within--duration: ${duration}ms`}
>
    <defs>
      <clipPath id={clipMainId}>
          <path d={"M0 0h32v32h-32ZM6 16A1 1 0 0026 16 1 1 0 006 16"} />
      </clipPath>
    </defs>
    <g clip-path={`url(#${clipMainId})`}>
      <path d={"M30.7 21.3 27.1 16l3.7-5.3c.4-.5.1-1.3-.6-1.4l-6.3-1.1-1.1-6.3c-.1-.6-.8-.9-1.4-.6L16 5l-5.4-3.7c-.5-.4-1.3-.1-1.4.6l-1 6.3-6.4 1.1c-.6.1-.9.9-.6 1.3L4.9 16l-3.7 5.3c-.4.5-.1 1.3.6 1.4l6.3 1.1 1.1 6.3c.1.6.8.9 1.4.6l5.3-3.7 5.3 3.7c.5.4 1.3.1 1.4-.6l1.1-6.3 6.3-1.1c.8-.1 1.1-.8.7-1.4zM16 25.1c-5.1 0-9.1-4.1-9.1-9.1 0-5.1 4.1-9.1 9.1-9.1s9.1 4.1 9.1 9.1c0 5.1-4 9.1-9.1 9.1z"} class={clsx("[transform-origin:center]", "toggles-dev--[transform-origin:center]", "[transition:transform_var(--toggles-within--duration)_cubic-bezier(0,0,0,1.25)]", "toggles-dev--[transition:transform_var(--toggles-within--duration)_cubic-bezier(0,0,0,1.25)]", "dark:[transform:scale(0.65)]", "dark:toggles-dev--[transform:scale(0.65)]")} />
    </g>
    <path d={"M16 7.7c-4.6 0-8.2 3.7-8.2 8.2s3.6 8.4 8.2 8.4 8.2-3.7 8.2-8.2-3.6-8.4-8.2-8.4zm0 14.4c-3.4 0-6.1-2.9-6.1-6.2s2.7-6.1 6.1-6.1c3.4 0 6.1 2.9 6.1 6.2s-2.7 6.1-6.1 6.1z"} class={clsx("[transform-origin:center]", "toggles-dev--[transform-origin:center]", "[transition:transform_var(--toggles-within--duration)_cubic-bezier(0,0,0,1.25)]", "toggles-dev--[transition:transform_var(--toggles-within--duration)_cubic-bezier(0,0,0,1.25)]", "dark:[transform:scale(1.5)]", "dark:toggles-dev--[transform:scale(1.5)]")} />
    <path d={"M16 9.5c-3.6 0-6.4 2.9-6.4 6.4s2.8 6.5 6.4 6.5 6.4-2.9 6.4-6.4-2.8-6.5-6.4-6.5z"} class={clsx("[transform-origin:center]", "toggles-dev--[transform-origin:center]", "[transition:transform_var(--toggles-within--duration)_cubic-bezier(0,0,0,1.25)]", "toggles-dev--[transition:transform_var(--toggles-within--duration)_cubic-bezier(0,0,0,1.25)]", "dark:[transform:translate3d(3px,-3px,0)_scale(1.2)]", "dark:toggles-dev--[transform:translate3d(3px,-3px,0)_scale(1.2)]")} />
</svg>
</button>
