// packages/vue/src/Simple.vue
<script lang="ts">
  let nextId = 0;
</script>

<script setup lang="ts">
  import { useAttrs } from "vue";

  export interface Props {
    duration?: number;
    toggled?: boolean;
    type?: "button" | "submit" | "reset";
    title?: string;
    ariaLabel?: string;
  }

  const props = withDefaults(defineProps<Props>(), {
    duration: 500,
    type: "button",
    title: "Toggle theme",
    ariaLabel: "Toggle theme",
  });

  const attrs = useAttrs();

  const toggleId = `simple-${++nextId}`;

  const clipMainId = `toggles.dev-simple-main-${toggleId}`;


</script>

<template>
  <button
    v-bind="attrs"
    :type="props.type"
    :title="props.title"
    :aria-label="props.ariaLabel"
    :aria-pressed="props.toggled ?? attrs['aria-pressed']"
    :class="props.toggled === true ? 'dark' : props.toggled === false ? 'light' : undefined"
  >
<svg
  width="1em"
  height="1em"
  viewBox="0 0 32 32"
  aria-hidden="true"
  :fill="&quot;currentColor&quot;"
  :style="{ '--toggles-simple--duration': `${props.duration}ms` }"
>
    <defs>
      <clipPath :id="clipMainId">
          <path :d="&quot;M0-5h55v37h-55zm32 12a1 1 0 0025 0 1 1 0 00-25 0&quot;" :class="&quot;transition-[d,translate] duration-(--toggles-simple--duration) [transition-timing-function:cubic-bezier(0,0,0.15,1.25)] dark:[d:path('M-18-1h55v37h-55zm32_12a1_1_0_0025_0_1_1_0_00-25_0')] dark:not-supports-[d:path('M0_0')]:-translate-x-[19px] dark:not-supports-[d:path('M0_0')]:translate-y-[5px]&quot;" />
      </clipPath>
    </defs>
    <g :clip-path="`url(#${clipMainId})`">
      <circle :cx="16" :cy="16" :r="15" />
    </g>
</svg>
  </button>
</template>

// packages/react/src/toggles/Simple.tsx
import "../../../../css/simple.min.css";
import React, { useState, forwardRef } from "react";
import { ToggleProps } from "../";
const SvgSimple = forwardRef<HTMLButtonElement, ToggleProps>((props: ToggleProps, ref) => {
  const {
    onToggle,
    toggled,
    toggle,
    duration = 500,
    reversed = false,
    title = "Toggle theme",
    style,
    "aria-label": ariaLabel = "Toggle theme",
    className,
    ...rest
  } = props;
  const [toggledInternal, toggleInternal] = useState(false);
  const toggleFunction = toggle || toggleInternal;
  const isToggled = toggled !== undefined ? toggled : toggledInternal;
  const btnClass = `theme-toggle ${isToggled ? "theme-toggle--toggled" : ""} ${reversed ? "theme-toggle--reversed" : ""} ${className ? className : ""}`.trim();
  const btnStyle = { ...style,
    "--theme-toggle__simple--duration": `${duration}ms`
  };

  const handleClick = () => {
    const mToggled = !isToggled;
    toggleFunction(mToggled);
    onToggle && onToggle(mToggled);
  };

  return <button ref={ref} className={btnClass} style={btnStyle} aria-label={ariaLabel} title={title} onClick={handleClick} {...rest}>
            {<svg xmlns="http://www.w3.org/2000/svg" aria-hidden="true" width="1em" height="1em" className="theme-toggle__simple" fill="currentColor" viewBox="0 0 32 32"><clipPath id="theme-toggle__simple__cutout"><path d="M0-5h55v37h-55zm32 12a1 1 0 0025 0 1 1 0 00-25 0" /></clipPath><g clipPath="url(#theme-toggle__simple__cutout)"><circle cx={16} cy={16} r={15} /></g></svg>}
          </button>;
});
export default SvgSimple;
